### ISSUE TITLE
In stage 8,how to get the info hash to do GET request and discover peers?

### ISSUE THREAD

**Issue by cyz6668** [codecrafters-io/build-your-own-bittorrent#13]
![image](https://github.com/codecrafters-io/build-your-own-bittorrent/assets/31882593/17ab1856-bfe1-4a19-9ab4-2f27f7ea6327)

In this task, I wrote in this way, but I got failed.
![image](https://github.com/codecrafters-io/build-your-own-bittorrent/assets/31882593/0ab409b3-a97d-4d3a-94b4-2acd01f18a91)
![image](https://github.com/codecrafters-io/build-your-own-bittorrent/assets/31882593/d9bce30a-2703-4421-9990-66ce72d18165)

**Comment by sarp** [comment]
Sorry for late reply, please use `#debugging-help-bittorrent` on Discord to get help faster. You can join with this link: https://discord.com/invite/DeqUD2P

You just need to call `digest()` to convert the SHA-1 object to a byte array. Instead of `hashlib.sha1(bencode_info)` you would pass in `hashlib.sha1(bencode_info).digest()`
